# Generated by Django 4.1.2 on 2022-10-13 16:01

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('hacker_item_id', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], default='story', max_length=7)),
                ('time', models.CharField(default=1665676896, max_length=50)),
                ('by', models.CharField(default=api.utils.generate_random_id, max_length=50)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_hacker_item', models.BooleanField(default=True)),
                ('time_added_to_db', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
