# Generated by Django 4.1.2 on 2022-10-13 16:32

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='by',
            field=models.CharField(default=api.utils.generate_random_id, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(default=1665678722, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
