# Generated by Django 4.1.2 on 2022-10-10 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_id_alter_item_time_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time_added_to_db',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(default=1665415563, max_length=50),
        ),
    ]
